add syntax highlighting for output
itaysk/kubectl-neat pull request #52
Opened 2020-12-30 14:19 UTC by karuppiah7890

fixes #39

2020-12-30 14:20 UTC, karuppiah7890 commented
Consider this a draft. Of course we can first discuss and make any necessary changes and then merge :)

2020-12-30 14:21 UTC, karuppiah7890 commented
It currently looks like this

<img width="1205" alt="Screen Shot 2020-12-30 at 7 51 05 PM" src="https://user-images.githubusercontent.com/12808424/103357103-5c7cb480-4ad8-11eb-84cf-1b10ffde072a.png">

2020-12-30 14:22 UTC, karuppiah7890 commented
With yaml, the output looks nice, but with JSON, it doesn't look that great actually, even though JSON is only a subset of YAML

![Uploading Screen Shot 2020-12-30 at 7.52.09 PM.png…]()

2020-12-30 14:27 UTC, karuppiah7890 commented
And I haven't added any unit or E2E test. I was wondering if we should test it and what to test and how to do it.

Should we add just E2E test? Since it's more CLI output related. I can't think of anything related to unit test, but I can see that there are some unit tests around output. We could do that.

Any thoughts on testing?

2020-12-30 14:34 UTC, AssafKatz3 commented
> 
> 
> And I haven't added any unit or E2E test. I was wondering if we should test it and what to test and how to do it.
> 
> Should we add just E2E test? Since it's more CLI output related. I can't think of anything related to unit test, but I can see that there are some unit tests around output. We could do that.
> 
> Any thoughts on testing?

1. Check that the option has impact (different output) for JSON & YAML with/without this option
2. Check that error code is consistent with and without this option
3. Check that writing it twice pass correctly
4. Check that the first line of both YAML & JSON output contains color sequence
5. Check the color of YAML by reread the output and checking that all color sequences are in place (It is problematic for JSON since it will fail for numbers)

2020-12-30 15:00 UTC, karuppiah7890 commented
Could you explain more about what points 2 and 3 mean? I didn't understand them properly

2020-12-30 15:07 UTC, AssafKatz3 commented
> 
> 
> Could you explain more about what points 2, 3 and 5 mean? I didn't understand them properly

2 - Ensure that if the command failed without color, it is failing with color also
3 - Call command with "-c -c" and see that it is working
5 - Call command with color, read the output and compare it to what should be the output (with color character sequences)

2020-12-30 15:20 UTC, karuppiah7890 commented
What's the benefit of 4 (single line check) if 5 does a complete check?

2020-12-30 15:22 UTC, AssafKatz3 commented
> 
> 
> What's the benefit of 4 (single line check) if 5 does a complete check?

4 is working for JSON also, I agree that for YAML is redundant if you will do also 5.

2020-12-30 15:26 UTC, karuppiah7890 commented
About 2 - Why would the error code change because of this option? Only when highlighting has some issues (error), there will be a non-zero exit code

2020-12-30 15:28 UTC, AssafKatz3 commented
> 
> 
> About 2 - Why would the error code change because of this option? Only when highlighting has some issues (error), there will be a non-zero exit code

It shouldn't - this is reason why need such test (I had such bug 20 years ago and it was really nagging)

2020-12-30 15:39 UTC, karuppiah7890 commented
Makes sense. I'll add it.

But I was just wondering, so, the test strategy is -

For every feature flag that's present, test if the usage of any flag causes the exit code to change in an unexpected manner? Doesn't that sound tedious? Or it could be done as some sort of parameterized test, but still that would be a lot of combinations depending on the number of flags and possible error situations

2020-12-30 15:42 UTC, AssafKatz3 commented
> This project doesn't have much flags, so all good. Just wondering in general 😅

I think that this is question for @itaysk and should be documented somewhere.

2020-12-30 15:43 UTC, karuppiah7890 commented
Cool. I thought you would have an answer since you suggested the strategy

2020-12-30 15:59 UTC, karuppiah7890 commented
Another thing is, I have only written code for the root command. I'm yet to understand and try out the "get" sub command. If it needs the color, we need to add for it too

2020-12-30 16:02 UTC, karuppiah7890 commented
Do we surely need the full output check? I think we can trust the library and just check that the option works - that is, invokes the library, by just checking the first line

2020-12-30 16:03 UTC, AssafKatz3 commented
> 
> 
> Do we surely need the full output check? I think we can trust the library and just check that the option works - that is, invokes the library, by just checking the first line

I am not sure this why I split it to two different tests.

2020-12-30 20:07 UTC, karuppiah7890 commented
I have finished all the stuff for this PR. cc @itaysk

2020-12-30 20:08 UTC, karuppiah7890 commented
You can review and let me know how it looks and if there are any more changes to be done :)

2020-12-31 05:34 UTC, AssafKatz3 commented
@karuppiah7890 
[The library that this code rely on](https://github.com/andreazorzetto/yh/blob/master/highlight/highlight.go), which in turn depended on [another library which isn't working well on Windows](https://github.com/logrusorgru/aurora#windows). I didn't check it personally, but it is something to check (manually at least) :-(

2020-12-31 06:17 UTC, karuppiah7890 commented
@AssafKatz3 cool, I'll check it out! Currently we still don't have support for windows however (no artifacts) but yeah, I'll be sure to check it out

2021-01-10 21:09 UTC, itaysk requested changes

2021-01-10 21:09 UTC, itaysk commented on cmd/cmd.go
> +func printOutput(cmd *cobra.Command, out []byte) error {
instead of passing the entire cmd, can you please in just `cmd.OutOrStdout()` as `io.writer`?

2021-01-10 21:09 UTC, itaysk commented on cmd/cmd.go
> +		cmd.Println(highlightedOutput)
please rebase and use `Print` based on https://github.com/itaysk/kubectl-neat/pull/57

2021-06-02 10:15 UTC, karuppiah7890 commented
Apparently the library may not work on Windows - https://github.com/itaysk/kubectl-neat/pull/52#issuecomment-752850500 . I'm not working on this PR now, so I'll close it. I hope new contributors will have an opportunity to work on it and also check support for windows based on #6 , #53

2021-10-03 16:44 UTC, karuppiah7890 commented
I'll resume working on this soon

2022-09-15 11:57 UTC, closed without merging